[build]
  command = "ng build --configuration production --aot"
  publish = "dist/music-all-web-app"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
